name:                ticTacToeGui
version:             0.1.0.0
github:              "githubuser/ticTacToeGui"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ticTacToeGui#readme>

dependencies:
- base >= 4.7 && < 5
- threepenny-gui
- filepath
- random
- array
- mtl
#- snap-core-1.0.5.1
#- snap-server-1.1.2.1
#- readable-0.3.1
#- websockets-snap-0.10.3.1
#- io-streams-haproxy-1.0.1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ticTacToeGui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ticTacToeGui

tests:
  ticTacToeGui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ticTacToeGui
